name: megan mack
favicon: null
layout_spectrum: 0.1740604203660041
typography_spectrum: 0.7095568249933422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6364927655085921
  lightness: 0.7772060937713832
  saturation: 0.7915732352994382
  rhythmicContrast: 0.48287963261827826
purpose: []
